### ISSUE TITLE
当前项目使用了 less，请安装插件 @tarojs/plugin-less，并且在 plugins 中进行配置，否则将无法编译 less 文件！

### ISSUE THREAD

**Issue by johnson7788** [jiechud/taro-mall#16]
请问这个报错怎么解决呢，插件已经安装了

yarn dev:h5
yarn run v1.22.4
$ npm run build:h5 -- --watch
npm WARN lifecycle The node binary used for scripts is /var/folders/n2/ym10fk_j0j107g25n_cg6dh00000gp/T/yarn--1592543138084-0.1295911085660233/node but npm is using /usr/local/Cellar/node/10.8.0/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> xiaochengxu-shop@1.0.0 build:h5 /Users/admin/git/taro-mall
> taro build --type h5 "--watch"

👽 Taro v2.2.9

当前项目使用了 less，请安装插件 @tarojs/plugin-less，并且在 plugins 中进行配置，否则将无法编译 less 文件！
参考文档：https://nervjs.github.io/taro/docs/config-detail#plugins

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! xiaochengxu-shop@1.0.0 build:h5: `taro build --type h5 "--watch"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the xiaochengxu-shop@1.0.0 build:h5 script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/admin/.npm/_logs/2020-06-19T05_05_40_615Z-debug.log
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by sedationh** [comment]
`import Taro, { Component } from '@tarojs/taro'
import { Provider } from '@tarojs/redux'
// import 'taro-ui/dist/style/index.scss';
import dva from './dva';
import models from './models';

import Index from './pages/index'`
去掉第三行 依然能用

**Comment by wizard-a** [comment]
@SedationH 可能是新版本做了组件按需加载

**Comment by wizard-a** [comment]
@johnson7788 项目已升级到 2.2.9，请获取最新代码
