### ISSUE TITLE
项目运行问题

### ISSUE THREAD

**Issue by roger858** [jiechud/taro-mall#20]
npm run dev:h5
提示 Module not found: Can't resolve 'F:\TaroProjects\taro-mall\src\app.config' in 'F:\TaroProjects\taro-mall'

自己补充了src\app.config.js 之后 ，页面空白, console 提示
[HMR] Waiting for update signal from WDS...
[WDS] Hot Module Replacement enabled.

什么原因呢？

**Comment by firma** [comment]
看下taro版本，如果是3就选择降级 到 taro update self 2.2.9

**Comment by wizard-a** [comment]
现在项目已经升级到taro3.x
