### ISSUE TITLE
全部页面空白问题

### ISSUE THREAD

**Issue by my-petrichor** [jiechud/taro-mall#40]
克隆项目后，修改 package.json 文件内部 taro 版本为 3.3.9 进行依赖拉取，编译完成后通过微信开发者工具查看页面全部为空白，截图如下：
![image](https://user-images.githubusercontent.com/69021934/136500112-337e010c-1d72-420c-b420-119e7620abaf.png)
请问我该如何解决，谢谢！

**Comment by wizard-a** [comment]
提供下报错信息

**Comment by wizard-a** [comment]
taro 版本已更新
