### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by Corleone-M** [jiechud/taro-mall#49]
Failed to compile.
./src/app.config.js
Module build failed (from @tarojs/taro-loader/lib/h5):
TypeError: Cannot destructure property 'importFrameworkStatement' of 'options.loaderMeta' as it is undefined.

**Comment by ignite-404** [comment]
我也遇到了相同问题
好像被GitHub的dependa bot修改了啥配置，退回几个commit就好了
对了 记得把taro cli改的和项目一致：
taro update self 3.0.25
然后再install

On Apr 2, 2022, at 3:05 AM, Corleone ***@***.***> wrote:

﻿

Failed to compile.
./src/app.config.js
Module build failed (from @tarojs/taro-loader/lib/h5):
TypeError: Cannot destructure property 'importFrameworkStatement' of 'options.loaderMeta' as it is undefined.

**Comment by wizard-a** [comment]
taro版本已升级，请更新试一下，感谢 @Jamesxiehailong  贡献
