### ISSUE TITLE
运行后页面几乎空白

### ISSUE THREAD

**Issue by nuohy** [jiechud/taro-mall#7]
taro: 2.0.4，
> npm i 
> npm run dev:h5
运行后，有警告：
'../../../services/coupon' does not contain an export named 'CouponSelectList'.
" '@tarojs/redux-h5' does not contain an export named 'useDispatch'.
" '@tarojs/redux-h5' does not contain an export named 'useSelector'.
请问项目需要修改什么地方么？

**Comment by wizard-a** [comment]
加自定义底部导航引起的，自定义底部导航用了 hooks， taro对h5的hooks还不支持。

**Comment by wizard-a** [comment]
拉下最新代码，在试一下吧
