### ISSUE TITLE
h5 dev编译报错和请求数据问题

### ISSUE THREAD

**Issue by LBC100** [jiechud/taro-mall#9]
总结: 1.开发环境编译的时候报错.  2. 请求数据的时候也报错了.
环境: mac.  h5开发
报错如下图

![image](https://user-images.githubusercontent.com/38514123/80208358-9b618d00-8662-11ea-8a66-623829ca86c2.png)

![image](https://user-images.githubusercontent.com/38514123/80208455-d663c080-8662-11ea-87ba-4048266a2ac8.png)

Compiled with warnings.

./.temp/pages/ucenter/couponSelect/couponSelect.js 49:8-24
" '../../../services/coupon' does not contain an export named 'CouponSelectList'.

./.temp/components/tab-bar/index.js 35:21-32
" '@tarojs/redux-h5' does not contain an export named 'useDispatch'.

./.temp/components/tab-bar/index.js 29:25-36
" '@tarojs/redux-h5' does not contain an export named 'useSelector'.

**Comment by wizard-a** [comment]
已修复
